const MESSAGE_TYPES = {
  MODE_INIT: "mode_init",
  TILE_TOGGLE: "tile_toggle",
  COUNT_UPDATE: "count_update",
  SYNC: "sync",
  RESET: "reset",
  TURN_UPDATE: "turn_update",
  GUESS_REQUEST: "guess_request",
  GUESS_RESULT: "guess_result"
};

const dom = {
  modeSelect: document.getElementById("modeSelect"),
  createOfferBtn: document.getElementById("createOfferBtn"),
  copySignalBtn: document.getElementById("copySignalBtn"),
  connectionPanel: document.getElementById("connectionPanel"),
  connectionPanelToggle: document.getElementById("connectionPanelToggle"),
  createAnswerBtn: document.getElementById("createAnswerBtn"),
  acceptAnswerBtn: document.getElementById("acceptAnswerBtn"),
  undoBtn: document.getElementById("undoBtn"),
  resyncBtn: document.getElementById("resyncBtn"),
  resetBtn: document.getElementById("resetBtn"),
  localSignalOutput: document.getElementById("localSignalOutput"),
  remoteSignalInput: document.getElementById("remoteSignalInput"),
  whatsappSignalBtn: document.getElementById("whatsappSignalBtn"),
  whatsappRemoteBtn: document.getElementById("whatsappRemoteBtn"),
  pasteRemoteBtn: document.getElementById("pasteRemoteBtn"),
  statusText: document.getElementById("statusText"),
  connectionPill: document.getElementById("connectionPill"),
  yourRemainingCount: document.getElementById("yourRemainingCount"),
  opponentRemainingCount: document.getElementById("opponentRemainingCount"),
  opponentScoreCard: document.getElementById("opponentScoreCard"),
  turnStatusCard: document.getElementById("turnStatusCard"),
  turnStatusValue: document.getElementById("turnStatusValue"),
  passControlBtn: document.getElementById("passControlBtn"),
  secretPanelContainer: document.getElementById("secretPanelContainer"),
  yourBoardContainer: document.getElementById("yourBoardContainer"),
  opponentBoardContainer: document.getElementById("opponentBoardContainer"),
  boardInfo: document.getElementById("boardInfo"),
  roundResultOverlay: document.getElementById("roundResultOverlay"),
  roundResultCard: document.getElementById("roundResultCard"),
  roundResultEmoji: document.getElementById("roundResultEmoji"),
  roundResultTitle: document.getElementById("roundResultTitle"),
  roundResultBody: document.getElementById("roundResultBody"),
  newGameBtn: document.getElementById("newGameBtn"),
  confettiField: document.getElementById("confettiField"),
  startGameSection: document.getElementById("startGameSection"),
  startGameBtn: document.getElementById("startGameBtn"),
  themeToggle: document.getElementById("themeToggle"),
  themeIcon: document.querySelector(".theme-icon")
};