const GAME_MODES = {
  office: {
    id: "office",
    label: "The Office US",
    boardSize: 25,
    extensions: [".webp"],
    characters: [
      { id: "michael_scott", name: "Michael Scott", accent: ["#d4af37", "#f4e04d"] },
      { id: "dwight_schrute", name: "Dwight Schrute", accent: ["#3d5c1f", "#5a7d2e"] },
      { id: "jim_halpert", name: "Jim Halpert", accent: ["#35654d", "#4f8a6d"] },
      { id: "pam_beesley", name: "Pam Beesly", accent: ["#e8b4b8", "#d4919a"] },
      { id: "kevin_malone", name: "Kevin Malone", accent: ["#8b4513", "#a0522d"] },
      { id: "creed_bratton", name: "Creed Bratton", accent: ["#556b2f", "#6b8e23"] },
      { id: "holly_flax", name: "Holly Flax", accent: ["#cd853f", "#daa520"] },
      { id: "angela_martin", name: "Angela Martin", accent: ["#696969", "#808080"] },
      { id: "toby_flenderson", name: "Toby Flenderson", accent: ["#b8860b", "#daa520"] },
      { id: "stanley_hudson", name: "Stanley Hudson", accent: ["#2f4f4f", "#3d5c5c"] },
      { id: "darryl_philbin", name: "Darryl Philbin", accent: ["#191970", "#4169e1"] },
      { id: "phyllis_vance", name: "Phyllis Vance", accent: ["#800080", "#9932cc"] },
      { id: "oscar_martinez", name: "Oscar Martinez", accent: ["#4682b4", "#5f9ea0"] },
      { id: "karen_filippelli", name: "Karen Filippelli", accent: ["#bc8f8f", "#cd5c5c"] },
      { id: "erin_hannon", name: "Erin Hannon", accent: ["#ff69b4", "#ff1493"] },
      { id: "jan_levinson", name: "Jan Levinson", accent: ["#000000", "#2f2f2f"] },
      { id: "andy_bernard", name: "Andy Bernard", accent: ["#ff4500", "#ff6347"] },
      { id: "kelly_kapoor", name: "Kelly Kapoor", accent: ["#ff00ff", "#ff1493"] },
      { id: "meredith_palmer", name: "Meredith Palmer", accent: ["#ff8c00", "#ffa500"] },
      { id: "ryan_howard", name: "Ryan Howard", accent: ["#000080", "#191970"] },
      { id: "robert_california", name: "Robert California", accent: ["#f5f5f5", "#d3d3d3"] },
      { id: "roy_anderson", name: "Roy Anderson", accent: ["#8b0000", "#a52a2a"] },
      { id: "gabe_lewis", name: "Gabe Lewis", accent: ["#4b0082", "#6a0dad"] },
      { id: "nellie_bertram", name: "Nellie Bertram", accent: ["#d87093", "#db7093"] },
      { id: "todd_packer", name: "Todd Packer", accent: ["#556b2f", "#6b8e23"] }
    ]
  },
  bollywood: {
    id: "bollywood",
    label: "Bollywood Celebrities",
    boardSize: 25,
    extensions: [".jpg", ".jpeg", ".png"],
    characters: [
      { id: "shah_rukh_khan", name: "Shah Rukh Khan", accent: ["#4568dc", "#b06ab3"] },
      { id: "salman_khan", name: "Salman Khan", accent: ["#11998e", "#38ef7d"] },
      { id: "aamir_khan", name: "Aamir Khan", accent: ["#1d2b64", "#f8cdda"] },
      { id: "hrithik_roshan", name: "Hrithik Roshan", accent: ["#4b6cb7", "#182848"] },
      { id: "ranbir_kapoor", name: "Ranbir Kapoor", accent: ["#c33764", "#1d2671"] },
      { id: "ranveer_singh", name: "Ranveer Singh", accent: ["#f46b45", "#eea849"] },
      { id: "ajay_devgn", name: "Ajay Devgn", accent: ["#134e5e", "#71b280"] },
      { id: "akshay_kumar", name: "Akshay Kumar", accent: ["#3a1c71", "#d76d77"] },
      { id: "amitabh_bachchan", name: "Amitabh Bachchan", accent: ["#42275a", "#734b6d"] },
      { id: "saif_ali_khan", name: "Saif Ali Khan", accent: ["#0f2027", "#2c5364"] },
      { id: "deepika_padukone", name: "Deepika Padukone", accent: ["#355c7d", "#6c5b7b"] },
      { id: "priyanka_chopra", name: "Priyanka Chopra", accent: ["#614385", "#516395"] },
      { id: "alia_bhatt", name: "Alia Bhatt", accent: ["#ff758c", "#ff7eb3"] },
      { id: "kareena_kapoor", name: "Kareena Kapoor", accent: ["#cc2b5e", "#753a88"] },
      { id: "katrina_kaif", name: "Katrina Kaif", accent: ["#7f00ff", "#e100ff"] },
      { id: "anushka_sharma", name: "Anushka Sharma", accent: ["#11998e", "#0575e6"] },
      { id: "madhuri_dixit", name: "Madhuri Dixit", accent: ["#ff512f", "#dd2476"] },
      { id: "kajol", name: "Kajol", accent: ["#8360c3", "#2ebf91"] },
      { id: "vidya_balan", name: "Vidya Balan", accent: ["#41295a", "#2f0743"] },
      { id: "kiara_advani", name: "Kiara Advani", accent: ["#4776e6", "#8e54e9"] },
      { id: "shahid_kapoor", name: "Shahid Kapoor", accent: ["#11998e", "#38ef7d"] },
      { id: "varun_dhawan", name: "Varun Dhawan", accent: ["#f46b45", "#eea849"] },
      { id: "ayushmann_khurrana", name: "Ayushmann Khurrana", accent: ["#134e5e", "#71b280"] },
      { id: "shraddha_kapoor", name: "Shraddha Kapoor", accent: ["#ff758c", "#ff7eb3"] },
      { id: "tara_sutaria", name: "Tara Sutaria", accent: ["#4776e6", "#8e54e9"] }
    ]
  },
  clashofclans: {
    id: "clashofclans",
    label: "Clash of Clans",
    boardSize: 25,
    extensions: [".webp", ".png"],
    characters: [
      { id: "barbarian", name: "Barbarian", accent: ["#d4881f", "#f5a623"] },
      { id: "archer", name: "Archer", accent: ["#bd10e0", "#7a0e9b"] },
      { id: "giant", name: "Giant", accent: ["#7ed321", "#5d9c1c"] },
      { id: "wizard", name: "Wizard", accent: ["#4a90e2", "#2d6eb5"] },
      { id: "dragon", name: "Dragon", accent: ["#f5a623", "#b8a04f"] },
      { id: "goblin", name: "Goblin", accent: ["#7ed321", "#56a816"] },
      { id: "pekka", name: "PEKKA", accent: ["#4a90e2", "#1a3d70"] },
      { id: "miner", name: "Miner", accent: ["#f5a623", "#a67b28"] },
      { id: "archer_queen", name: "Archer Queen", accent: ["#bd10e0", "#9a10b8"] },
      { id: "barbarian_king", name: "Barbarian King", accent: ["#f5a623", "#c98818"] },
      { id: "valkyrie", name: "Valkyrie", accent: ["#d4881f", "#f5a623"] },
      { id: "witch", name: "Witch", accent: ["#4a90e2", "#332ab8"] },
      { id: "healer", name: "Healer", accent: ["#f5a623", "#e8c265"] },
      { id: "balloon", name: "Balloon", accent: ["#f5a623", "#aa7b1a"] },
      { id: "baby_dragon", name: "Baby Dragon", accent: ["#7ed321", "#4d8a12"] },
      { id: "yeti", name: "Yeti", accent: ["#4a90e2", "#86b4f5"] },
      { id: "electro_dragon", name: "Electro Dragon", accent: ["#f5a623", "#bfb026"] },
      { id: "ice_golem", name: "Ice Golem", accent: ["#4a90e2", "#2d5696"] },
      { id: "root_rider", name: "Root Rider", accent: ["#7ed321", "#3d7a10"] },
      { id: "druid", name: "Druid", accent: ["#7ed321", "#4c8c1b"] },
      { id: "lava_hound", name: "Lava Hound", accent: ["#d4881f", "#da7c20"] },
      { id: "golem", name: "Golem", accent: ["#f5a623", "#a67b28"] },
      { id: "wall_breaker", name: "Wall Breaker", accent: ["#d4881f", "#f5a623"] },
      { id: "hog_rider", name: "Hog Rider", accent: ["#7ed321", "#5d9c1c"] },
      { id: "bowler", name: "Bowler", accent: ["#4a90e2", "#2d6eb5"] },
      { id: "dragon_duke", name: "Dragon Duke", accent: ["#f5a623", "#b8a04f"] },
      { id: "dragon_rider", name: "Dragon Rider", accent: ["#f5a623", "#b8a04f"] },
      { id: "grand_warden", name: "Grand Warden", accent: ["#4a90e2", "#86b4f5"] },
      { id: "minion", name: "Minion", accent: ["#7ed321", "#5d9c1c"] },
      { id: "minion_prince", name: "Minion Prince", accent: ["#7ed321", "#5d9c1c"] },
      { id: "thrower", name: "Thrower", accent: ["#4a90e2", "#2d6eb5"] },
      { id: "headhunter", name: "Headhunter", accent: ["#4a90e2", "#2d6eb5"] },
      { id: "meteor_golem", name: "Meteor Golem", accent: ["#f5a623", "#a67b28"] },
      { id: "royal_champion", name: "Royal Champion", accent: ["#bd10e0", "#9a10b8"] },
      { id: "battle_copter", name: "Battle Copter", accent: ["#4a90e2", "#2d6eb5"] },
      { id: "battle_machine", name: "Battle Machine", accent: ["#4a90e2", "#2d6eb5"] },
      { id: "apprentice_warden", name: "Apprentice Warden", accent: ["#4a90e2", "#86b4f5"] },
      { id: "electro_titan", name: "Electro Titan", accent: ["#f5a623", "#bfb026"] },
      { id: "furnace", name: "Furnace", accent: ["#f5a623", "#aa7b1a"] }
    ]
  },
  tv_shows: {
    id: "tv_shows",
    label: "TV Shows",
    boardSize: 25,
    extensions: [".webp"],
    characters: [
      { id: "michael_scott", name: "Michael Scott", accent: ["#d4af37", "#f4e04d"] },
      { id: "dwight_schrute", name: "Dwight Schrute", accent: ["#3d5c1f", "#5a7d2e"] },
      { id: "jim_halpert", name: "Jim Halpert", accent: ["#35654d", "#4f8a6d"] },
      { id: "pam_beesley", name: "Pam Beesly", accent: ["#e8b4b8", "#d4919a"] },
      { id: "kevin_malone", name: "Kevin Malone", accent: ["#8b4513", "#a0522d"] },
      { id: "creed_bratton", name: "Creed Bratton", accent: ["#556b2f", "#6b8e23"] },
      { id: "angela_martin", name: "Angela Martin", accent: ["#696969", "#808080"] },
      { id: "toby_flenderson", name: "Toby Flenderson", accent: ["#b8860b", "#daa520"] },
      { id: "stanley_hudson", name: "Stanley Hudson", accent: ["#2f4f4f", "#3d5c5c"] },
      { id: "darryl_philbin", name: "Darryl Philbin", accent: ["#191970", "#4169e1"] },
      { id: "phyllis_vance", name: "Phyllis Vance", accent: ["#800080", "#9932cc"] },
      { id: "oscar_martinez", name: "Oscar Martinez", accent: ["#4682b4", "#5f9ea0"] },
      { id: "kelly_kapoor", name: "Kelly Kapoor", accent: ["#ff00ff", "#ff1493"] },
      { id: "meredith_palmer", name: "Meredith Palmer", accent: ["#ff8c00", "#ffa500"] },
      { id: "ryan_howard", name: "Ryan Howard", accent: ["#000080", "#191970"] },
      { id: "ross_geller", name: "Ross Geller", accent: ["#8b4513", "#cd853f"] },
      { id: "rachel_green", name: "Rachel Green", accent: ["#dda0dd", "#ba55d3"] },
      { id: "chandler_bing", name: "Chandler Bing", accent: ["#4169e1", "#87ceeb"] },
      { id: "monica_geller", name: "Monica Geller", accent: ["#ff69b4", "#ff1493"] },
      { id: "joey_tribbiani", name: "Joey Tribbiani", accent: ["#ff4500", "#ff6347"] },
      { id: "phoebe_buffay", name: "Phoebe Buffay", accent: ["#9370db", "#8a2be2"] },
      { id: "gunther", name: "Gunther", accent: ["#8b4513", "#a0522d"] },
      { id: "janice", name: "Janice", accent: ["#ff6347", "#ffa07a"] },
      { id: "jake_peralta", name: "Jake Peralta", accent: ["#1e3a5f", "#3498db"] },
      { id: "amy_santiago", name: "Amy Santiago", accent: ["#2980b9", "#3498db"] },
      { id: "charles_boyle", name: "Charles Boyle", accent: ["#27ae60", "#2ecc71"] },
      { id: "raymond_holt", name: "Raymond Holt", accent: ["#1e3a5f", "#2c3e50"] },
      { id: "rosa_diaz", name: "Rosa Diaz", accent: ["#8e44ad", "#9b59b6"] },
      { id: "walter_white", name: "Walter White", accent: ["#7cb342", "#558b2f"] },
      { id: "jesse_pinkman", name: "Jesse Pinkman", accent: ["#ff7043", "#ff5722"] },
      { id: "skylar_white", name: "Skylar White", accent: ["#607d8b", "#78909c"] },
      { id: "hank_schrader", name: "Hank Schrader", accent: ["#1e3a5f", "#2980b9"] },
      { id: "gus_fring", name: "Gus Fring", accent: ["#fdd835", "#212121"] },
      { id: "mike_ehrmantraut", name: "Mike Ehrmantraut", accent: ["#424242", "#616161"] },
      { id: "saul_goodman", name: "Saul Goodman", accent: ["#ffd700", "#ff8c00"] },
      { id: "jon_snow", name: "Jon Snow", accent: ["#2c3e50", "#bdc3c7"] },
      { id: "daenerys_targaryen", name: "Daenerys Targaryen", accent: ["#f5a623", "#ffffff"] },
      { id: "arya_stark", name: "Arya Stark", accent: ["#2c3e50", "#34495e"] },
      { id: "sansa_stark", name: "Sansa Stark", accent: ["#8b0000", "#c0c0c0"] },
      { id: "tyrion_lannister", name: "Tyrion Lannister", accent: ["#ffd700", "#8b0000"] },
      { id: "cersei_lannister", name: "Cersei Lannister", accent: ["#8b0000", "#ffd700"] },
      { id: "jaime_lannister", name: "Jaime Lannister", accent: ["#ffd700", "#8b4513"] },
      { id: "joffrey_baratheon", name: "Joffrey Baratheon", accent: ["#8b0000", "#2c3e50"] },
      { id: "phil_dunphy", name: "Phil Dunphy", accent: ["#f39c12", "#e67e22"] },
      { id: "claire_dunphy", name: "Claire Dunphy", accent: ["#9b59b6", "#8e44ad"] },
      { id: "alex_dunphy", name: "Alex Dunphy", accent: ["#3498db", "#2980b9"] },
      { id: "haley_dunphy", name: "Haley Dunphy", accent: ["#e74c3c", "#c0392b"] },
      { id: "luke_dunphy", name: "Luke Dunphy", accent: ["#2ecc71", "#27ae60"] },
      { id: "manny_delgado", name: "Manny Delgado", accent: ["#e67e22", "#d35400"] },
      { id: "jay_pritchett", name: "Jay Pritchett", accent: ["#1e3a5f", "#34495e"] },
      { id: "gloria_pritchett", name: "Gloria Pritchett", accent: ["#e74c3c", "#c0392b"] },
      { id: "sheldon_cooper", name: "Sheldon Cooper", accent: ["#3498db", "#9b59b6"] },
      { id: "leonard_hofstadter", name: "Leonard Hofstadter", accent: ["#3498db", "#9b59b6"] },
      { id: "amy_farrah_fowler", name: "Amy Farrah Fowler", accent: ["#9b59b6", "#8e44ad"] },
      { id: "penny", name: "Penny", accent: ["#f39c12", "#e67e22"] },
      { id: "rajesh_koothrappali", name: "Rajesh Koothrappali", accent: ["#3498db", "#9b59b6"] },
      { id: "howard_wolowitz", name: "Howard Wolowitz", accent: ["#3498db", "#9b59b6"] },
      { id: "bernadette_rostenkowski", name: "Bernadette Rostenkowski", accent: ["#e91e63", "#f48fb1"] },
      { id: "eleven", name: "Eleven", accent: ["#e74c3c", "#c0392b"] },
      { id: "jim_hopper", name: "Jim Hopper", accent: ["#1e3a5f", "#2c3e50"] },
      { id: "max_mayfield", name: "Max Mayfield", accent: ["#e74c3c", "#ff5722"] },
      { id: "lucas_sinclair", name: "Lucas Sinclair", accent: ["#2ecc71", "#27ae60"] },
      { id: "dustin_henderson", name: "Dustin Henderson", accent: ["#f39c12", "#e67e22"] },
      { id: "steve_harrington", name: "Steve Harrington", accent: ["#8b4513", "#a0522d"] },
      { id: "will_byers", name: "Will Byers", accent: ["#3498db", "#2980b9"] },
      { id: "nancy_wheeler", name: "Nancy Wheeler", accent: ["#9b59b6", "#8e44ad"] },
      { id: "mike_wheeler", name: "Mike Wheeler", accent: ["#2ecc71", "#27ae60"] },
      { id: "barney_stinson", name: "Barney Stinson", accent: ["#f39c12", "#3498db"] },
      { id: "ted_mosby", name: "Ted Mosby", accent: ["#e67e22", "#f39c12"] },
      { id: "marshall_eriksen", name: "Marshall Eriksen", accent: ["#3498db", "#2980b9"] },
      { id: "lily_alrin", name: "Lily Alrin", accent: ["#e91e63", "#f48fb1"] },
      { id: "robin_scherbatsky", name: "Robin Scherbatsky", accent: ["#3498db", "#e74c3c"] }
    ]
  },
  marvel: {
    id: "marvel",
    label: "Marvel",
    boardSize: 25,
    extensions: [".webp"],
    characters: [
      { id: "iron_man", name: "Iron Man", accent: ["#c62828", "#ffd700"] },
      { id: "steve_rogers", name: "Steve Rogers", accent: ["#1565c0", "#c62828"] },
      { id: "thor", name: "Thor", accent: ["#ff8f00", "#1565c0"] },
      { id: "hulk", name: "Hulk", accent: ["#2e7d32", "#795548"] },
      { id: "black_widow", name: "Black Widow", accent: ["#880e4f", "#212121"] },
      { id: "hawkeye", name: "Hawkeye", accent: ["#5d4037", "#ffc107"] },
      { id: "scarlet_witch", name: "Scarlet Witch", accent: ["#6a1b9a", "#d50000"] },
      { id: "vision", name: "Vision", accent: ["#00bcd4", "#ff9800"] },
      { id: "spider_man", name: "Spider-Man", accent: ["#c62828", "#1565c0"] },
      { id: "doctor_strange", name: "Doctor Strange", accent: ["#311b92", "#ffab00"] },
      { id: "ant_man", name: "Ant-Man", accent: ["#c62828", "#fbc02d"] },
      { id: "wasp", name: "Wasp", accent: ["#c62828", "#fbc02d"] },
      { id: "captain_marvel", name: "Captain Marvel", accent: ["#c62828", "#ffd700"] },
      { id: "black_panther", name: "Black Panther", accent: ["#212121", "#9c27b0"] },
      { id: "wolverine", name: "Wolverine", accent: ["#f9a825", "#c62828"] },
      { id: "deadpool", name: "Deadpool", accent: ["#c62828", "#212121"] },
      { id: "thanos", name: "Thanos", accent: ["#9c27b0", "#ffeb3b"] },
      { id: "loki", name: "Loki", accent: ["#2e7d32", "#ffd700"] },
      { id: "groot", name: "Groot", accent: ["#2e7d32", "#795548"] },
      { id: "rocket", name: "Rocket", accent: ["#795548", "#ffc107"] },
      { id: "gamora", name: "Gamora", accent: ["#2e7d32", "#7b1fa2"] },
      { id: "nebula", name: "Nebula", accent: ["#212121", "#7b1fa2"] },
      { id: "star_lord", name: "Star-Lord", accent: ["#ff9800", "#00bcd4"] },
      { id: "mantis", name: "Mantis", accent: ["#aed581", "#8bc34a"] },
      { id: "korg", name: "Korg", accent: ["#795548", "#9e9e9e"] },
      { id: "ronan", name: "Ronan", accent: ["#212121", "#ffc107"] },
      { id: "ego", name: "Ego", accent: ["#ffeb3b", "#00bcd4"] },
      { id: "yondu", name: "Yondu", accent: ["#212121", "#c62828"] },
      { id: "war_machine", name: "War Machine", accent: ["#212121", "#c62828"] },
      { id: "falcon", name: "Falcon", accent: ["#c62828", "#212121"] },
      { id: "winter_soldier", name: "Winter Soldier", accent: ["#212121", "#9e9e9e"] },
      { id: "pepper_potts", name: "Pepper Potts", accent: ["#c62828", "#ffd700"] },
      { id: "nick_fury", name: "Nick Fury", accent: ["#212121", "#9e9e9e"] },
      { id: "maria_hill", name: "Maria Hill", accent: ["#212121", "#2196f3"] },
      { id: "phil_coulson", name: "Phil Coulson", accent: ["#2196f3", "#212121"] },
      { id: "peggy_carter", name: "Peggy Carter", accent: ["#c62828", "#ffd700"] },
      { id: "howard_stark", name: "Howard Stark", accent: ["#ffd700", "#c62828"] },
      { id: "shuri", name: "Shuri", accent: ["#9c27b0", "#00bcd4"] },
      { id: "mighty_thor", name: "Mighty Thor", accent: ["#ff8f00", "#1565c0"] },
      { id: "hela", name: "Hela", accent: ["#2e7d32", "#880e4f"] },
      { id: "odin", name: "Odin", accent: ["#ffd700", "#1565c0"] },
      { id: "zeus", name: "Zeus", accent: ["#ffd700", "#ff8f00"] },
      { id: "gorr", name: "Gorr", accent: ["#212121", "#880e4f"] },
      { id: "kang_the_conqueror", name: "Kang the Conqueror", accent: ["#c62828", "#ffc107"] },
      { id: "ultron", name: "Ultron", accent: ["#ffc107", "#c62828"] },
      { id: "doctor_doom", name: "Doctor Doom", accent: ["#2e7d32", "#ffd700"] },
      { id: "modok", name: "MODOK", accent: ["#1565c0", "#c62828"] },
      { id: "daredevil", name: "Daredevil", accent: ["#c62828", "#212121"] },
      { id: "punisher", name: "Punisher", accent: ["#212121", "#424242"] },
      { id: "killmonger", name: "Killmonger", accent: ["#9c27b0", "#ffd700"] },
      { id: "shang_chi", name: "Shang-Chi", accent: ["#c62828", "#ffd700"] },
      { id: "valkyrie", name: "Valkyrie", accent: ["#1565c0", "#ffd700"] },
      { id: "red_hulk", name: "Red Hulk", accent: ["#c62828", "#795548"] },
      { id: "ancient_one", name: "Ancient One", accent: ["#311b92", "#ffd700"] },
      { id: "wong", name: "Wong", accent: ["#311b92", "#ffc107"] },
      { id: "janet_van_dyne", name: "Janet van Dyne", accent: ["#c62828", "#ffd700"] },
      { id: "obadiah_stane", name: "Obadiah Stane", accent: ["#424242", "#c62828"] }
    ]
  }
};

function getAvailableModes() {
  return Object.keys(GAME_MODES).map(key => ({
    id: key,
    label: GAME_MODES[key].label
  }));
}

function getModeById(modeId) {
  return GAME_MODES[modeId] || null;
}

function getCharacterCountForMode(modeId) {
  const mode = getModeById(modeId);
  return mode ? (mode.boardSize || 25) : 0;
}

function populateModeSelect(selectId) {
  const select = document.getElementById(selectId);
  if (!select) return;
  
  select.innerHTML = "";
  const modes = getAvailableModes();
  modes.forEach(mode => {
    const option = document.createElement("option");
    option.value = mode.id;
    option.textContent = mode.label;
    select.appendChild(option);
  });
}